on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact for this package.'
        required: false
        type: string
        default: package
      overwrite-publish-config:
        description: 'Changes the publish config registry URL.'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.output.outputs.artifact-path }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download JSON
        uses: actions/download-artifact@v4
        with:
          name: package-json

      - name: Download Changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Modify package.json for Publish Config
        if: ${{ inputs.overwrite-publish-config != '' }}
        run: |
          jq --arg publishConfig "${{ inputs.overwrite-publish-config }}" '. + {"publishConfig": {"registry": $publishConfig}}' package.json > tmp.$$.json
          mv tmp.$$.json package.json
        shell: bash

      - name: Modify package.json for Git Repository URL
        run: |
          GIT_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          jq --arg gitUrl "$GIT_URL" '. + {"repository": $gitUrl}' package.json > tmp.$$.json
          mv tmp.$$.json package.json
        shell: bash

      - name: Pack
        run: npm pack
        shell: bash

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: "*.tgz"
          retention-days: 30